#!/bin/bash
set -eu

PACKAGE_NAME=$1
PACKAGE_VERSION=$2
TIMEOUT=${3-30}
DELAY_BETWEEN_REQUESTS=${4-1}

timeout --foreground -s TERM $TIMEOUT ./check_pip.sh $PACKAGE_NAME $PACKAGE_VERSION $TIMEOUT $DELAY_BETWEEN_REQUESTS