#!/bin/bash
set -eux

PACKAGE_NAME=$1
PACKAGE_VERSION=$2
TIMEOUT=${3-30}
DELAY_BETWEEN_REQUESTS=${4-1}

SCRIPT_PATH=${GITHUB_ACTION_PATH-.}

timeout --foreground -s TERM $TIMEOUT $SCRIPT_PATH/check_pip.sh $PACKAGE_NAME $PACKAGE_VERSION $TIMEOUT $DELAY_BETWEEN_REQUESTS